### ISSUE TITLE
running with pytest > 3.0.3

### ISSUE THREAD

**Issue by JornVernee** [EVEprosper/ProsperCommon#7]
Hey, I was watching EVE Prosper - EP081 and I decided to clone the repo to just have a look around. I ran the test command (`python setup.py test`) and it came back with a `VersionConflict`:

    pkg_resources.VersionConflict: (pytest 3.0.5 (j:\winpython-64bit-3.5.1.2\python-3.5.1.amd64\lib\site-packages), Requirement.parse('pytest==3.0.3'))

Seems I have `pytest` 3.0.5, but it requires 3.0.3 . Maybe that should be `pytest>=3.0.3` ? Or something like `pytest==3.0.x`? Or, maybe it's an auto generated check. I don't how to change it though.

For now, it does look like `pip` can install specific versions of the package with; 

    pip install pytest==3.0.3

**Comment by lockefox** [comment]
good point.  Have made requirements less strict/pedantic.  Using "minimum version" for now until we run into new issues.

Should be fixed in v0.3.8
