### ISSUE TITLE
First time test running throws `FileNotFoundError`

### ISSUE THREAD

**Issue by JornVernee** [EVEprosper/ProsperCommon#8]
Running tests for the first time (as in, re-running them works fine), A `FileNotFoundError` is thrown;

```
_________________________ test_cleanup_log_directory __________________________

log_builder_obj = None
config = <prosper.common.prosper_config.ProsperConfig object at 0x0000023BB7AF6278>

    def test_cleanup_log_directory(
            log_builder_obj=None,
            config=TEST_CONFIG
    ):
        """Test0: clean up testing log directory.  Only want log-under-test"""
        if log_builder_obj:
            log_builder_obj.close_handles()

        print(path.exists(LOG_PATH))

>       log_list = listdir(LOG_PATH)
E       FileNotFoundError: [WinError 3] The system cannot find the path specified: 'logs'

test\logging_test.py:69: FileNotFoundError
---------------------------- Captured stdout call -----------------------------
False
=============== 1 failed, 11 passed, 13 skipped in 0.62 seconds ===============
```

It seems like it cannot find the newly created `logs` folder. Re-running the tests with the folder already existing doesn't cause the problem, but deleting it again does.

Simplest fix might just be to add a `logs` folder to the repo by default, or add an `if path.exists(...)` before the `listdir`. But there might be something else going on that causes this that I don't know about, and it seems to small to pull-request any ways.

Sorry if this is being too nitty, but I thought it might scare some people off, but sorry if this is being too nitty.

**Comment by lockefox** [comment]
It's a good point, and I just pushed a fix.

v0.3.8 should have fixes deployed
